
spring:
  datasource:
    username: shortlink
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/shortlink_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    lettuce:
      pool:
        max-active: 50
        min-idle: 10
        max-idle: 10
        max-wait: 100
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3
      nodes:
        - 127.0.0.1:6391
        - 127.0.0.1:6392
        - 127.0.0.1:6393
server:
  port: 80
mybatis:
  type-aliases-package: com.xxx.shortlink.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #加了这个配置之后就可以直接把下划线分隔的库表字段自动转换为camel格式，不再需要ResultMap
machine:
  no: 1

